services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    user: "mysql:mysql"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh
    command:
      - --require-secure-transport=OFF
    networks:
      - db_network

  wordpress:
    container_name: wordpress
    build: ./wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - ngx_network
      - db_network

  nginx:
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - ngx_network
    depends_on:
      - wordpress

volumes:
  db_data:
  wp_data:

networks:
  db_network:
    driver: bridge
  ngx_network:
    driver: bridge