services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    user: "mysql:mysql"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh
    command:
      - --require-secure-transport=OFF
    networks:
      - db_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2-fpm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
      - pma_data:/var/www/html
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=${MARIADB_USER}
      - PMA_PASSWORD=${MARIADB_USER_PASSWORD}
      - PMA_ABSOLUTE_URI=https://${HOSTNAME}/phpmyadmin/
    depends_on:
      - mariadb
    networks:
      - ngx_network
      - db_network

  wordpress:
    container_name: wordpress
    build: ./wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - ngx_network
      - db_network

  nginx:
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
      - pma_data:/var/www/html/phpmyadmin
    networks:
      - ngx_network
    depends_on:
      - wordpress

volumes:
  db_data:
  wp_data:
  pma_data:

networks:
  db_network:
    driver: bridge
  ngx_network:
    driver: bridge