#!/bin/bash
set -ex

mysql -u root -p"${MARIADB_ROOT_PASSWORD}" <<EOF
CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MARIADB_DATABASE}.* TO '${MARIADB_USER}'@'%' WITH GRANT OPTION;
GRANT SELECT ON mysql.user TO '${MARIADB_USER}'@'%';
FLUSH PRIVILEGES;
EOF