
- become: true # Exec with sudo
  hosts: all
  name: base-config

  vars:
    droplet_root_password: "{{ lookup('ini', 'DROPLET_ROOT_PASSWORD file=../.env') }}"
    droplet_username: "{{ lookup('ini', 'DROPLET_USERNAME file=../.env') }}"
    droplet_password: "{{ lookup('ini', 'DROPLET_USER_PASSWORD file=../.env') }}"

  tasks:
      
    - name: Wait for system to become available after update
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 3600


    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ droplet_root_password | ansible.builtin.password_hash('sha512') }}"
        shell: /bin/bash


    - name: Add user "{{ droplet_username }}"
      ansible.builtin.user:
        name: "{{ droplet_username }}"
        password: "{{ droplet_password | ansible.builtin.password_hash('sha512') }}"
        groups: sudo
        append: yes
        shell: /bin/bash


    - name: Add SSH key to "{{ droplet_username }}"
      ansible.posix.authorized_key:
        user: "{{ droplet_username }}"
        state: present
        key: "{{ lookup('ansible.builtin.file', './id_rsa.pub') }}"
    

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      retries: 10
      delay: 5


    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        lock_timeout: 360
        state: latest
        update_cache: true
      retries: 10
      delay: 5


    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      retries: 5
      delay: 5


    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      retries: 5
      delay: 5


    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
        lock_timeout: 360
      retries: 10
      delay: 5


    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
        version: "6.1.0"


    - name: Ensure Docker is enabled and started
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started


    - name: Add "{{ droplet_username }}"" to group docker
      ansible.builtin.user:
        name: "{{ droplet_username }}"
        groups: docker
        append: yes


    - name: Copy srcs folder to VM /home/{{ droplet_username }}/cloud-1
      ansible.builtin.copy:
        src: ../srcs/
        dest: /home/{{ droplet_username }}/cloud-1/
        remote_src: no


    - name: Change .env hostname
      ansible.builtin.shell: |
        sed -i "s/HOSTNAME=localhost/HOSTNAME={{ inventory_hostname }}/g" /home/{{ droplet_username }}/cloud-1/.env


    - name: Deploy docker project
      community.docker.docker_compose_v2:
        project_src: /home/{{ droplet_username }}/cloud-1
        files:
          - docker-compose.yml
        state: present
        recreate: always
        pull: missing
        build: policy
      retries: 2
      delay: 5

