
- become: yes
  hosts: all
  name: base-config
  vars:
    droplet_root_password: "{{ lookup('ini', 'DROPLET_ROOT_PASSWD file=../.env') }}"
    droplet_username: "{{ lookup('ini', 'DROPLET_USERNAME file=../.env') }}"
    droplet_password: "{{ lookup('ini', 'DROPLET_USER_PASSWD file=../.env') }}"

  tasks:
    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ droplet_root_password | ansible.builtin.password_hash('sha512') }}"
        shell: /bin/bash

    - name: Add user "{{ droplet_username }}"
      ansible.builtin.user:
        name: "{{ droplet_username }}"
        password: "{{ droplet_password | ansible.builtin.password_hash('sha512') }}"
        groups: sudo
        append: yes
        shell: /bin/bash

    - name: Add SSH key to "{{ droplet_username }}"
      ansible.posix.authorized_key:
        user: "{{ droplet_username }}"
        state: present
        key: "{{ lookup('ansible.builtin.file', './id_rsa.pub') }}"
      